FROM golang:1.24.5

WORKDIR /go/src
ENV PATH="/go/bin:${PATH}"
ENV GO111MODULE=on
ENV CGO_ENABLED=1

RUN set -ex && \
    apt-get update && \
    apt-get install -y build-essential protobuf-compiler librdkafka-dev && \
    go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest && \
    go install google.golang.org/protobuf/cmd/protoc-gen-go@latest && \
    go install github.com/spf13/cobra-cli@latest && \
    go install github.com/air-verse/air@latest && \
    go install github.com/swaggo/swag/cmd/swag@latest && \
    wget https://github.com/ktr0731/evans/releases/download/0.9.1/evans_linux_amd64.tar.gz && \
    tar -xzvf evans_linux_amd64.tar.gz && \
    mv evans /usr/local/bin && \
    rm -f evans_linux_amd64.tar.gz

CMD ["air", "-c", ".air.toml"]